name: WakaTime Status Update
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"
